/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ScientificRevisionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/data.ts
var DEFAULT_DATA = {
  topics: []
};
function getToday() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
function addDays(dateStr, days) {
  const d = new Date(dateStr + "T12:00:00Z");
  d.setDate(d.getDate() + days);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}-${String(d.getUTCDate()).padStart(2, "0")}`;
}
function isOverdue(targetDate, today) {
  return targetDate < today;
}

// src/algorithm.ts
function calculateNextInterval(quality, currentInterval, currentEaseFactor) {
  let newEaseFactor = currentEaseFactor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
  if (newEaseFactor < 1.3) {
    newEaseFactor = 1.3;
  }
  let newInterval = 1;
  if (quality < 3) {
    newInterval = 1;
  } else {
    if (currentInterval === 0) {
      newInterval = 1;
    } else if (currentInterval === 1) {
      newInterval = 6;
    } else {
      newInterval = Math.round(currentInterval * currentEaseFactor);
    }
  }
  return {
    interval: newInterval,
    easeFactor: newEaseFactor
  };
}

// src/ui/TrackerView.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_TRACKER = "scientific-revision-tracker";
var TrackerView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeTab = "dashboard";
    this.currentMonthOffset = 0;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TRACKER;
  }
  getDisplayText() {
    return "Study Tracker";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    const tabsContainer = container.createDiv({ cls: "tracker-tabs" });
    const dashTab = tabsContainer.createDiv({ cls: `tracker-tab ${this.activeTab === "dashboard" ? "active" : ""}`, text: "Dashboard" });
    const calTab = tabsContainer.createDiv({ cls: `tracker-tab ${this.activeTab === "calendar" ? "active" : ""}`, text: "Calendar" });
    dashTab.addEventListener("click", () => {
      this.activeTab = "dashboard";
      this.render();
    });
    calTab.addEventListener("click", () => {
      this.activeTab = "calendar";
      this.render();
    });
    const contentContainer = container.createDiv({ cls: "tracker-content" });
    if (this.activeTab === "dashboard") {
      this.renderDashboard(contentContainer);
    } else {
      this.renderCalendar(contentContainer);
    }
  }
  renderDashboard(container) {
    const today = getToday();
    const topics = this.plugin.pluginData.topics;
    const overdueTopics = topics.filter((t) => t.state === "studied" && isOverdue(t.targetDate, today));
    const toStudyToday = topics.filter((t) => t.state === "planned" && t.targetDate <= today);
    const toReviseToday = topics.filter((t) => t.state === "studied" && t.targetDate === today);
    const inputContainer = container.createDiv({ cls: "tracker-input-container" });
    const input = inputContainer.createEl("input", { type: "text", placeholder: "Log a new topic (e.g. [[Physics]])" });
    const addButton = inputContainer.createEl("button", { text: "Add for Today" });
    addButton.addEventListener("click", async () => {
      if (input.value.trim()) {
        const newTopic = {
          id: Date.now().toString(),
          name: input.value.trim(),
          state: "planned",
          targetDate: today,
          interval: 0,
          easeFactor: 2.5
        };
        this.plugin.pluginData.topics.push(newTopic);
        await this.plugin.savePluginData();
        input.value = "";
        this.render();
      }
    });
    if (overdueTopics.length > 0) {
      const overdueDetails = container.createEl("details", { cls: "tracker-section overdue-section" });
      overdueDetails.setAttribute("open", "");
      overdueDetails.createEl("summary", { text: `\u26A0\uFE0F Overdue Revisions [${overdueTopics.length}]` });
      this.renderTopicList(overdueDetails, overdueTopics);
    }
    const reviseDetails = container.createEl("details", { cls: "tracker-section" });
    reviseDetails.setAttribute("open", "");
    reviseDetails.createEl("summary", { text: `\u{1F504} To Revise Today [${toReviseToday.length}]` });
    if (toReviseToday.length === 0) {
      reviseDetails.createEl("p", { text: "No revisions scheduled for today." });
    } else {
      this.renderTopicList(reviseDetails, toReviseToday);
    }
    const studyDetails = container.createEl("details", { cls: "tracker-section" });
    studyDetails.createEl("summary", { text: `\u{1F4DA} To Study Today [${toStudyToday.length}]` });
    if (toStudyToday.length === 0) {
      studyDetails.createEl("p", { text: "No new topics planned for today." });
    } else {
      this.renderTopicList(studyDetails, toStudyToday);
    }
    const next7Days = addDays(today, 7);
    const upcomingTopics = topics.filter((t) => t.state === "studied" && t.targetDate > today && t.targetDate <= next7Days);
    upcomingTopics.sort((a, b) => a.targetDate.localeCompare(b.targetDate));
    if (upcomingTopics.length > 0) {
      const upcomingDetails = container.createEl("details", { cls: "tracker-section" });
      upcomingDetails.createEl("summary", { text: `\u{1F5D3}\uFE0F Upcoming Revisions (Next 7 Days) [${upcomingTopics.length}]` });
      this.renderTopicList(upcomingDetails, upcomingTopics, true);
    }
  }
  renderTopicList(container, topics, isReadOnly = false) {
    const list = container.createEl("ul");
    for (const topic of topics) {
      const li = list.createEl("li", { cls: "topic-item" });
      li.createSpan({ text: topic.name, cls: "topic-name" });
      if (isReadOnly) {
        li.createSpan({ text: `Due: ${topic.targetDate}`, cls: "topic-due-date" });
        continue;
      }
      const actions = li.createDiv({ cls: "topic-actions" });
      if (topic.state === "planned") {
        const btn = actions.createEl("button", { text: "Done" });
        btn.addEventListener("click", async () => {
          await this.plugin.handleStudyComplete(topic.id);
          this.render();
        });
      } else {
        const hardBtn = actions.createEl("button", { text: "Hard (1)", cls: "btn-hard" });
        const goodBtn = actions.createEl("button", { text: "Good (4)", cls: "btn-good" });
        const easyBtn = actions.createEl("button", { text: "Easy (5)", cls: "btn-easy" });
        hardBtn.addEventListener("click", () => this.handleGrade(topic.id, 1));
        goodBtn.addEventListener("click", () => this.handleGrade(topic.id, 4));
        easyBtn.addEventListener("click", () => this.handleGrade(topic.id, 5));
      }
    }
  }
  renderCalendar(container) {
    const today = new Date();
    const displayDate = new Date(today.getFullYear(), today.getMonth() + this.currentMonthOffset, 1);
    const header = container.createDiv({ cls: "calendar-header" });
    const prevBtn = header.createEl("button", { text: "\u25C0" });
    const title = header.createEl("strong", { text: displayDate.toLocaleDateString(void 0, { month: "long", year: "numeric" }) });
    const nextBtn = header.createEl("button", { text: "\u25B6" });
    prevBtn.addEventListener("click", () => {
      this.currentMonthOffset--;
      this.render();
    });
    nextBtn.addEventListener("click", () => {
      this.currentMonthOffset++;
      this.render();
    });
    const grid = container.createDiv({ cls: "calendar-grid" });
    ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].forEach((day) => {
      grid.createDiv({ cls: "calendar-day-header", text: day });
    });
    const daysInMonth = new Date(displayDate.getFullYear(), displayDate.getMonth() + 1, 0).getDate();
    const firstDayOfWeek = displayDate.getDay();
    for (let i = 0; i < firstDayOfWeek; i++) {
      grid.createDiv({ cls: "calendar-cell empty" });
    }
    const todayStr = getToday();
    for (let day = 1; day <= daysInMonth; day++) {
      const cellDate = new Date(displayDate.getFullYear(), displayDate.getMonth(), day);
      const dateStr = `${cellDate.getFullYear()}-${String(cellDate.getMonth() + 1).padStart(2, "0")}-${String(cellDate.getDate()).padStart(2, "0")}`;
      const cell = grid.createDiv({ cls: `calendar-cell ${dateStr === todayStr ? "today" : ""}` });
      cell.createDiv({ cls: "calendar-date-number", text: String(day) });
      cell.addEventListener("dragover", (e) => {
        e.preventDefault();
        cell.addClass("drag-over");
      });
      cell.addEventListener("dragleave", () => {
        cell.removeClass("drag-over");
      });
      cell.addEventListener("drop", async (e) => {
        var _a;
        e.preventDefault();
        cell.removeClass("drag-over");
        const topicId = (_a = e.dataTransfer) == null ? void 0 : _a.getData("text/plain");
        if (topicId) {
          await this.handleTopicDrop(topicId, dateStr);
        }
      });
      const dayTopics = this.plugin.pluginData.topics.filter((t) => t.targetDate === dateStr);
      for (const topic of dayTopics) {
        const topicEl = cell.createDiv({
          cls: `calendar-topic-item ${topic.state}`,
          text: topic.name
        });
        topicEl.setAttr("draggable", "true");
        topicEl.addEventListener("dragstart", (e) => {
          var _a;
          (_a = e.dataTransfer) == null ? void 0 : _a.setData("text/plain", topic.id);
          topicEl.addClass("dragging");
        });
        topicEl.addEventListener("dragend", () => {
          topicEl.removeClass("dragging");
        });
      }
    }
  }
  async handleTopicDrop(topicId, newDate) {
    const topic = this.plugin.pluginData.topics.find((t) => t.id === topicId);
    if (!topic || topic.targetDate === newDate)
      return;
    if (topic.state === "studied" && newDate > topic.targetDate) {
      new import_obsidian.Notice("\u26A0\uFE0F Warning: Delaying a scheduled algorithmic revision risks forgetting the material!");
    }
    topic.targetDate = newDate;
    await this.plugin.savePluginData();
    this.render();
  }
  async handleGrade(topicId, quality) {
    await this.plugin.handleRevisionGrade(topicId, quality);
    this.render();
  }
};

// src/main.ts
var ScientificRevisionPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    console.log("Loading Scientific Revision Plugin");
    await this.loadPluginData();
    this.registerView(
      VIEW_TYPE_TRACKER,
      (leaf) => new TrackerView(leaf, this)
    );
    this.addRibbonIcon("calendar-check", "Study Tracker", () => {
      this.activateView();
    });
  }
  async onunload() {
    console.log("Unloading Scientific Revision Plugin");
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_TRACKER);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_TRACKER, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async loadPluginData() {
    try {
      const loadedData = await this.loadData();
      this.pluginData = Object.assign({}, DEFAULT_DATA, loadedData);
    } catch (error) {
      console.error("Failed to load plugin data", error);
      this.pluginData = Object.assign({}, DEFAULT_DATA);
    }
  }
  async savePluginData() {
    try {
      await this.saveData(this.pluginData);
    } catch (error) {
      console.error("Failed to save plugin data", error);
    }
  }
  async handleStudyComplete(topicId) {
    const topic = this.pluginData.topics.find((t) => t.id === topicId);
    if (topic) {
      topic.state = "studied";
      topic.interval = 1;
      topic.easeFactor = 2.5;
      topic.lastReviewDate = getToday();
      topic.targetDate = addDays(getToday(), 1);
      await this.savePluginData();
    }
  }
  async handleRevisionGrade(topicId, quality) {
    const topic = this.pluginData.topics.find((t) => t.id === topicId);
    if (topic) {
      const result = calculateNextInterval(quality, topic.interval, topic.easeFactor);
      topic.interval = result.interval;
      topic.easeFactor = result.easeFactor;
      topic.lastReviewDate = getToday();
      topic.targetDate = addDays(getToday(), topic.interval);
      await this.savePluginData();
    }
  }
};
