/* THIS IS A GENERATED/BUNDLED FILE BY ESBUILD */
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ScientificRevisionPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/data.ts
var DEFAULT_DATA = {
  topics: []
};
function getToday() {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
}
function addDays(dateStr, days) {
  const d = new Date(dateStr + "T12:00:00Z");
  d.setDate(d.getDate() + days);
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, "0")}-${String(d.getUTCDate()).padStart(2, "0")}`;
}
function isOverdue(targetDate, today) {
  return targetDate < today;
}

// src/algorithm.ts
function calculateNextInterval(quality, currentInterval, currentEaseFactor) {
  let newEaseFactor = currentEaseFactor + (0.1 - (5 - quality) * (0.08 + (5 - quality) * 0.02));
  if (newEaseFactor < 1.3) {
    newEaseFactor = 1.3;
  }
  let newInterval = 1;
  if (quality < 3) {
    newInterval = 1;
  } else {
    if (currentInterval === 0) {
      newInterval = 1;
    } else if (currentInterval === 1) {
      newInterval = 6;
    } else {
      newInterval = Math.round(currentInterval * currentEaseFactor);
    }
  }
  return {
    interval: newInterval,
    easeFactor: newEaseFactor
  };
}

// src/ui/TrackerView.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_TRACKER = "scientific-revision-tracker";
var TrackerView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_TRACKER;
  }
  getDisplayText() {
    return "Study Tracker";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    const today = getToday();
    const topics = this.plugin.pluginData.topics;
    const overdueTopics = topics.filter((t) => t.state === "studied" && isOverdue(t.targetDate, today));
    const toStudyToday = topics.filter((t) => t.state === "planned" && t.targetDate === today);
    const toReviseToday = topics.filter((t) => t.state === "studied" && t.targetDate === today);
    const header = container.createEl("h2", { text: "Study & Revision Planner" });
    const inputContainer = container.createDiv({ cls: "tracker-input-container" });
    const input = inputContainer.createEl("input", { type: "text", placeholder: "Log a new topic (e.g. [[Physics]])" });
    const addButton = inputContainer.createEl("button", { text: "Add for Today" });
    addButton.addEventListener("click", async () => {
      if (input.value.trim()) {
        const newTopic = {
          id: Date.now().toString(),
          name: input.value.trim(),
          state: "planned",
          targetDate: today,
          interval: 0,
          easeFactor: 2.5
        };
        this.plugin.pluginData.topics.push(newTopic);
        await this.plugin.savePluginData();
        input.value = "";
        this.render();
      }
    });
    if (overdueTopics.length > 0) {
      const overdueContainer = container.createDiv({ cls: "tracker-section overdue-section" });
      overdueContainer.createEl("h3", { text: "\u26A0\uFE0F Overdue Revisions" });
      this.renderTopicList(overdueContainer, overdueTopics);
    }
    const reviseContainer = container.createDiv({ cls: "tracker-section" });
    reviseContainer.createEl("h3", { text: "\u{1F504} To Revise Today" });
    if (toReviseToday.length === 0) {
      reviseContainer.createEl("p", { text: "No revisions scheduled for today." });
    } else {
      this.renderTopicList(reviseContainer, toReviseToday);
    }
    const studyContainer = container.createDiv({ cls: "tracker-section" });
    studyContainer.createEl("h3", { text: "\u{1F4DA} To Study Today" });
    if (toStudyToday.length === 0) {
      studyContainer.createEl("p", { text: "No new topics planned for today." });
    } else {
      this.renderTopicList(studyContainer, toStudyToday);
    }
  }
  renderTopicList(container, topics) {
    const list = container.createEl("ul");
    for (const topic of topics) {
      const li = list.createEl("li", { cls: "topic-item" });
      li.createSpan({ text: topic.name, cls: "topic-name" });
      const actions = li.createDiv({ cls: "topic-actions" });
      if (topic.state === "planned") {
        const btn = actions.createEl("button", { text: "Done" });
        btn.addEventListener("click", async () => {
          await this.plugin.handleStudyComplete(topic.id);
          this.render();
        });
      } else {
        const hardBtn = actions.createEl("button", { text: "Hard (1)", cls: "btn-hard" });
        const goodBtn = actions.createEl("button", { text: "Good (4)", cls: "btn-good" });
        const easyBtn = actions.createEl("button", { text: "Easy (5)", cls: "btn-easy" });
        hardBtn.addEventListener("click", () => this.handleGrade(topic.id, 1));
        goodBtn.addEventListener("click", () => this.handleGrade(topic.id, 4));
        easyBtn.addEventListener("click", () => this.handleGrade(topic.id, 5));
      }
    }
  }
  async handleGrade(topicId, quality) {
    await this.plugin.handleRevisionGrade(topicId, quality);
    this.render();
  }
};

// src/main.ts
var ScientificRevisionPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    console.log("Loading Scientific Revision Plugin");
    await this.loadPluginData();
    this.registerView(
      VIEW_TYPE_TRACKER,
      (leaf) => new TrackerView(leaf, this)
    );
    this.addRibbonIcon("calendar-check", "Study Tracker", () => {
      this.activateView();
    });
  }
  async onunload() {
    console.log("Unloading Scientific Revision Plugin");
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_TRACKER);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await leaf.setViewState({ type: VIEW_TYPE_TRACKER, active: true });
    }
    workspace.revealLeaf(leaf);
  }
  async loadPluginData() {
    try {
      const loadedData = await this.loadData();
      this.pluginData = Object.assign({}, DEFAULT_DATA, loadedData);
    } catch (error) {
      console.error("Failed to load plugin data", error);
      this.pluginData = Object.assign({}, DEFAULT_DATA);
    }
  }
  async savePluginData() {
    try {
      await this.saveData(this.pluginData);
    } catch (error) {
      console.error("Failed to save plugin data", error);
    }
  }
  async handleStudyComplete(topicId) {
    const topic = this.pluginData.topics.find((t) => t.id === topicId);
    if (topic) {
      topic.state = "studied";
      topic.interval = 1;
      topic.easeFactor = 2.5;
      topic.lastReviewDate = getToday();
      topic.targetDate = addDays(getToday(), 1);
      await this.savePluginData();
    }
  }
  async handleRevisionGrade(topicId, quality) {
    const topic = this.pluginData.topics.find((t) => t.id === topicId);
    if (topic) {
      const result = calculateNextInterval(quality, topic.interval, topic.easeFactor);
      topic.interval = result.interval;
      topic.easeFactor = result.easeFactor;
      topic.lastReviewDate = getToday();
      topic.targetDate = addDays(getToday(), topic.interval);
      await this.savePluginData();
    }
  }
};
